Description: "Create SSM Parameter"
Parameters:
  DBPassword:
    NoEcho: 'true'
    Description: The WordPress database admin account password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
  DBRootPassword:
    NoEcho: 'true'
    Description: MySQL root password
    Type: String
    MinLength: '8'
    MaxLength: '41'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  DBPass:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "command"
      Name: /blakey/database/dbpassword
      Type: "String"
      Value: !Ref DBPassword
  DBRRootPass:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "command"
      Name: /blakey/database/dbrootpassword
      Type: "String"
      Value: !Ref DBRootPassword