---
AWSTemplateFormatVersion: '2010-09-09'
Description: ECS cluster shared components and entry point
Mappings: {}
Parameters:
  VpcId:
    Description: VPC ID which application servers will host in.
    Type: AWS::EC2::VPC::Id
  PrivateSubnet1:
    Description: Private subnet ID 1.
    Type: AWS::EC2::Subnet::Id
  PrivateSubnet2:
    Description: Private subnet ID 2.
    Type: AWS::EC2::Subnet::Id
  DbPassword:
    Type: String
    NoEcho: 'true'
    MinLength: '6'
    MaxLength: '20'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: must match pattern [a-zA-Z0-9] and be from 6 to 20 chars
      in length.
Resources:
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup
      SubnetIds:
      - Ref: PrivateSubnet1
      - Ref: PrivateSubnet2
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      VpcId:
        Ref: VpcId
      GroupDescription: Open database for access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '3306'
        ToPort: '3306'
  WordPressDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      StorageType: gp2
      DBInstanceClass: db.t2.micro
      Engine: MySQL
      MasterUsername: root
      MasterUserPassword:
        Ref: DbPassword
      VPCSecurityGroups:
      - Fn::GetAtt:
        - DBSecurityGroup
        - GroupId
      PubliclyAccessible: 'false'
      DBSubnetGroupName:
        Ref: DBSubnetGroup